using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Autodesk.Revit.DB;

namespace RvtVa3c
{
  //class Va3cFace
  //{
  //  ElementId ElementId { get; set; }
  //  int CategoryId { get; set; }
  //  ElementId MaterialId { get; set; }

  //  Va3cFace( 
  //    Element e, 
  //    ElementId material )
  //  {
  //    ElementId = e.Id;
  //    if( e.Category != null )
  //    {
  //      CategoryId = e.Category.Id.IntegerValue;
  //    }
  //    else
  //    {
  //      CategoryId = -1;
  //    }
  //    MaterialId = material;
  //  }
  //}
}
